### PR TITLE
Added larger domain boundaries to show graph less artistic

### PR DESCRIPTION
**Pull request by yasmin2496**
## Purpose
_Beautification of graph and match with ICLP_

## Further info
_Added larger domain boundaries to show graph less artistic_
_Removed duplicate timestamps captured on earlier data_

## Ticket number
_#130_

closing #130

### CODE REVIEW

**Review by RadhikaPPatel — CHANGES_REQUESTED** [review]
I guess mostly it is coming close to ICLP now, just increase the duration on X-axis.
In ICLP it has multiple sections for the same date as shown below

image

If you can get similar multiple intervals for the same date on X-axis on our UI I guess it will start looking the same to ICLP.

image

**Comment by yasmin2496** [comment]
Adding more date sections looks cluttered hence have removed it.

**Comment by RadhikaPPatel** [comment]
@yasmin2496 As discussed for now we can let X-axis be, but we will try to find the scroll option or other way to expand X-axis so that it does not look cluttered when we have multiple points for the same date.

**Review by RadhikaPPatel — APPROVED** [review]
Looks good

**Pull request merged**
