### PR TITLE
Disallow user to edit own core group or deactivate own account

### PR DESCRIPTION
**Pull request by andrewshortall**
## Purpose
On the user management screen:
- The user's own row should be disabled so they cannot accidentally remove their admin permissions
- The user should not see the 'Delete' action if a user is deactivated
- The user should not be able to change the permissions of their own core group

## Ticket number
#53

### CODE REVIEW

**Comment by RadhikaPPatel** [comment]
For Global and Organization Admin

1. I am still able to edit the name of the Group.
2. Also even though the group switches are disabled, click on the switch does make an API call to update the permission. Whereas it should not make the call at all.
**_Note:_** Right now it is failing with 400 as it needs organization in the API call .
image

Redux or Context issue (I guess)
Test Case: Logged in as Global Admin (admin). Went to User Management. Checked both tabs. Logged out. Logged in as Organization admin (radhikapatel). Went to User Management. So still admin is disabled whereas the user is radhikapatel.

image
image

Not a related issue.
Getting error in the inspector for the color property of EditIcon in InlineEditor.
image

**Comment by andrewshortall** [comment]
@RadhikaPPatel Good catch. I've disabled requests on groups without an organization. However, I think it's fine to edit the name of the user's own group (provided there's an org id). Unlike the permissions, there's not really any consequence to doing this.

**Review by RadhikaPPatel — CHANGES_REQUESTED** [review]
New code merged in master that needs to be brought here. Organization UUID changes.

**Comment by yasmin2496** [comment]
Added multi-tenancy support from https://github.com/TransparentPath/buildly-react-template/pull/49

**Pull request merged**
