### PR TITLE
Shipment Popup - Data loss prevention and redux cache persistence issue

### PR DESCRIPTION
**Pull request by yasmin2496**
## Purpose
_Added consistent checks for all subforms in shipment info_

## Further info
_Previously was missing for_
1. Items
2. Sensor & Gateway
3. Custodian
4. Shipment Key

## Ticket number
_#70_
_#180_ 

closing #70 
closing #180

### CODE REVIEW

**Review by RadhikaPPatel — CHANGES_REQUESTED** [review]
Please check unwanted popup and console errors

**Review by RadhikaPPatel — CHANGES_REQUESTED** [review]
Still having some issues with popup

**Comment by yasmin2496** [comment]
@RadhikaPPatel Handled checks for popup. Also added few checks on step change

**Comment by yasmin2496** [comment]
Screenshot 2021-05-11 at 11 16 29
Updated button text

**Review by RadhikaPPatel — APPROVED** [review]
Looks good

**Pull request merged**
