### PR TITLE
UI/reporting

### PR DESCRIPTION
**Pull request by TanmayJain92**
Added details table. Added option to download csv, excel or pdf files. Fixed localization issue in some data by exempting those for translating. Fixed organization drop down in top bar.

### CODE REVIEW

**Review by patelradhika — CHANGES_REQUESTED** [review]
Still shows the Producer org in the dropdown
image

**Comment by patelradhika** [comment]
When I click generate report it does not call the API for the email.

**Comment by patelradhika** [comment]
Origin and Destination are translated here which should be not
image

**Comment by TanmayJain92** [comment]
Above all fixed

**Review by patelradhika — APPROVED** [review]

**Pull request merged**
