### PR TITLE
Feat/refractor

### PR DESCRIPTION
**Pull request by TanmayJain92**
## Purpose
Performance improvements by replacing Redux to React-query.

### CODE REVIEW

**Comment by patelradhika** [comment]
@TanmayJain92 Please remove the redux code that is not being used anywhere after changes.

**Review by patelradhika — CHANGES_REQUESTED** [review]
Please remove the redux code that is not being used anywhere after changes.

**Comment by patelradhika** [comment]
Also please remove package-lock.json from the commit.

**Comment by TanmayJain92** [comment]
All changes done. Please have a review.

**Review by patelradhika — CHANGES_REQUESTED** [review]
There are performance issues on shipment and reporting page. Not sure why the queries are being triggered again and again and then the screen goes black.

**Comment by TanmayJain92** [comment]
Please have a review. For loaders please check for production. It is working fine.

**Review by patelradhika — CHANGES_REQUESTED** [review]
At some places you need to put check in place. For example say if we have shipments then only fetch custodies otherwise do not fetch the custody. So you need to add these kind of checks in place.

**Review by patelradhika — APPROVED** [review]
Look good. Issue notified but minor issue

**Pull request merged**
