### PR TITLE
Geofence Alerts when shipment is leaving or entering custody

### PR DESCRIPTION
**Pull request by yasmin2496**
## Purpose
_Trigger email alerts when shipment moves across custody geofences _

## Ticket number
_#127_

closing #127

### CODE REVIEW

**Comment by RadhikaPPatel** [comment]
Please fix this

image
image

Also, I am not able to see the notifications/alerts. Can you please check?

image

**Review by RadhikaPPatel — CHANGES_REQUESTED** [review]
few changes/correction suggested

**Comment by yasmin2496** [comment]
Fixed issues reported and suggestions provided

**Review by RadhikaPPatel — APPROVED** [review]
Looks good

**Pull request merged**
